chore: 🤖 Start boot with dependencies
utfpr/ppgcc-cm-datacapes-front pull request #1
Opened 2022-03-15 00:53 UTC by caiotheodoro

Start boot

2022-03-22 00:43 UTC, als-v approved these changes
Very good :clap:

2022-03-29 01:30 UTC, willianrod commented on components/ActiveLink.tsx
> +  }
```suggestion
  const isActive = useMemo(() => {
    return shouldMatchExactHref
      ? asPath == rest.href || asPath == rest.as
      : asPath.startsWith(String(rest.href))) || asPath.startsWith(String(rest.as)
  }, [asPath, shouldMatchExactHref, rest]);
```

2022-03-29 01:54 UTC, willianrod commented
Tenho um costume de sempre passar a imagem por um compressor para garantir que ela tem o menor tamanho possível sem começar a perder a qualidade. Passando o logo da UTFPR no tinypng, consegui uma redução de 68% no arquivo. Nesse caso pode não fazer muita diferença, mas em projetos grandes, alguns bits podem gerar uma boa economia no final do mês.

https://tinypng.com/

![image](https://user-images.githubusercontent.com/6539258/160516571-512cf810-34bb-4f96-b90f-a77309dab645.png)

2022-03-29 01:55 UTC, willianrod requested changes

2022-03-29 01:55 UTC, willianrod commented on components/Navbar/index.tsx
> +          onClose={() => onClose}
Não sei se teve algum motivo em específico para passar para o `onClose` um protótipo de uma função que retorna um protótipo da função `onClose`. Se não teve nenhum motivo em específico, poderia passar `onClose` direto

```suggestion
          onClose={onClose}
```

2022-03-29 01:55 UTC, willianrod commented on components/XMLUploadButton/index.tsx
> +        onChange={(e) => handleChange(e)}
Aqui você não precisa criar uma nova função para passar um parâmetro que a função já iria receber. Poderia passar `handleChange` direto.

```suggestion
        onChange={handleChange}
```

2022-03-29 01:55 UTC, willianrod commented on components/XMLUploadButton/index.tsx
> +    if (files?.name.split(".").pop() != "xml") {
Sempre dar preferência para utilizar o `!==` ou `===` para garantir que uma coisa seja realmente igual a outra.
Caso contrário você pode acabar tendo alguns comportamentos bizarros.

Exemplo:
![image](https://user-images.githubusercontent.com/6539258/160515487-ff368e9d-7185-4379-9ff9-4008af2a994e.png)


```suggestion
    if (files?.name.split(".").pop() !== "xml") {
```

2022-03-29 01:55 UTC, willianrod commented on package.json
> +    "git-cz": "^4.8.0",
Acredito que essas duas dependências sejam dependências de desenvolvimento, caso positivo, elas deveriam estar listadas nas devDependencies.

```suggestion
    "framer-motion": "^6.2.8",
```

2022-03-29 01:55 UTC, willianrod commented on pages/_app.tsx
> +        newestOnTop={true}
No JSX se você declara uma prop, por padrão ela vai assumir um valor verdadeiro. Você precisa apenas especificar seu valor, caso ele for falso.

```suggestion
        hideProgressBar={false}
        autoClose={3000}
        newestOnTop
```

2022-03-29 01:55 UTC, willianrod commented on pages/index.tsx
> +}
Você não precisa ter esse arquivo fazendo um redirect, você pode fazer um redirect no `next.config.js` e o next vai fazer esse redirect do lado do servidor. Do jeito atual você faz com que o next receba dois hits do cliente, um requisitando a pagina `index` e outro para navegar para a página `home`.

https://nextjs.org/docs/api-reference/next.config.js/redirects

Com o redirect no next.config.js, o servidor manda através de um status http que a página mudou de lugar já retornando o html da página correta.

Obs: Ao alterar o `next.config.js` em desenvolvimento você precisa reiniciar sua aplicação next para que as alterações sejam aplicadas.

2022-03-29 02:40 UTC, dennisurtubia approved these changes

2022-03-29 02:40 UTC, willianrod approved these changes

2022-03-29 16:10 UTC, dennisurtubia commented on package.json
> +  "devDependencies": {
@caiotheodoro acabou tirando as dependências de `dependencies` mas faltou incluir em `devDependencies`

```suggestion
  "devDependencies": {
  "commitizen": "^4.2.4",
    "framer-motion": "^6.2.8",
    "git-cz": "^4.8.0",
```

2022-03-30 00:34 UTC, dennisurtubia commented
@caiotheodoro tive impressão que estamos utilizando apenas o arquivo de logo `logo3.svg`, precisamos manter os outros?

2022-03-30 19:19 UTC, merged